# Generated by Django 4.0.1 on 2022-02-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_getimage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getimage',
            name='img',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='image'),
        ),
    ]
