# Generated by Django 4.0.1 on 2022-03-03 11:11

import django.core.files.storage
from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/feed/', location='C:\\Users\\tobyf\\Documents\\GitHub\\Group software project\\mysite\\media/feed/'), upload_to=polls.models.image_directory_path),
        ),
    ]
