# Generated by Django 4.0.1 on 2022-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
