# Generated by Django 4.0.1 on 2022-02-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_getimage_alter_image_img_delete_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getimage',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
