# Generated by Django 4.0.1 on 2022-02-28 17:22

import django.core.files.storage
from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_getimage_img_alter_image_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetImage',
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='C:\\Users\\Harry\\Documents\\GitHub\\ECM-2434-Group-Software-Engineering-Project\\mysite\\media/my_sell/'), upload_to=polls.models.image_directory_path),
        ),
        migrations.AlterModelTable(
            name='image',
            table='polls_image',
        ),
    ]
