# Generated by Django 4.0.1 on 2022-02-28 17:51

import django.core.files.storage
from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_delete_getimage_alter_image_img_alter_image_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/feed/', location='C:\\Users\\Harry\\Documents\\GitHub\\ECM-2434-Group-Software-Engineering-Project\\mysite\\media/feed/'), upload_to=polls.models.image_directory_path),
        ),
    ]
