# Generated by Django 4.0.1 on 2022-03-21 00:09

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0013_image_user_votes_alter_image_user_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/feed/', location='C:\\Users\\jacks\\OneDrive\\Documents\\GitHub\\ECM-2434-Group-Software-Engineering-Project\\mysite\\media/feed/'), upload_to=polls.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/feed/', location='C:\\Users\\jacks\\OneDrive\\Documents\\GitHub\\ECM-2434-Group-Software-Engineering-Project\\mysite\\media/feed/'), upload_to=polls.models.image_directory_path),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('badge_image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/feed/', location='C:\\Users\\jacks\\OneDrive\\Documents\\GitHub\\ECM-2434-Group-Software-Engineering-Project\\mysite\\media/feed/'), upload_to=polls.models.image_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
