# Generated by Django 4.0.1 on 2022-03-22 10:14

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_image_user_votes_alter_image_user_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='polls.challenge'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/feed/', location='C:\\Users\\jacks\\OneDrive\\Documents\\GitHub\\ECM-2434-Group-Software-Engineering-Project\\mysite\\media/feed/'), upload_to=polls.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/feed/', location='C:\\Users\\jacks\\OneDrive\\Documents\\GitHub\\ECM-2434-Group-Software-Engineering-Project\\mysite\\media/feed/'), upload_to=polls.models.image_directory_path),
        ),
    ]
