# Generated by Django 4.0.1 on 2022-03-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_image_img_alter_profile_img_badge'),
        ('polls', '0014_challenge_active_image_challenge_alter_image_img_and_more'),
    ]

    operations = [
    ]
