# Generated by Django 4.0.1 on 2022-03-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_merge_20220322_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
