# Generated by Django 4.0.1 on 2022-03-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_challenge_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
